force-app/main/default/objects/Proto_A_Quote__c/Proto_A_Quote__c.object-meta.xml
<CustomObject>
    <description>Holds quote lines that are just dummies that store files</description>
    <label>Proto A Quote</label>
    <nameField>
        <label>Proto Quote Alpha Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proto A Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proto_A_Quote_Line__c/Proto_A_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Proto A Quote Line</label>
    <nameField>
        <label>Proto A Quote Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proto A Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proto_A_Quote_Line__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>7</precision>
    <required>true</required>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Proto_A_Quote_Line__c/fields/Proto_A_Quote__c.field-meta.xml
<CustomField>
    <fullName>Proto_A_Quote__c</fullName>
    <label>Proto A Quote</label>
    <referenceTo>Proto_A_Quote__c</referenceTo>
    <relationshipLabel>Proto A Quote Lines</relationshipLabel>
    <relationshipName>Proto_A_Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proto_A_Quote_Line__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <label>Service Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteLogic.cls
public with sharing class QuoteLogic {

    static void quoteFileAttach(String quoteLineId, String fileName, Blob file){
        //maybe add searching later
        ContentVersion version = new ContentVersion();
        version.ContentLocation = 'S';
        version.PathOnClient = fileName;
        version.Title = fileName;
        version.versionData = file;
        insert version;

        Id versionDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE id =:version.Id].ContentDocumentId;
        ContentDocumentLink versionLink = new ContentDocumentLink();
        versionLink.ContentDocumentId = versionDoc;
        versionLink.LinkedEntityId = quoteLineId;
        versionLink.shareType = 'I';
        insert versionLink;
    }

    static Blob getQuoteFiles(String service, Decimal margin) {
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://rando-file-server.herokuapp.com');
        req.setTimeout(60000);
        req.setMethod('GET');

        HttpResponse res = h.send(req);
        Blob file_attachment = res.getBodyAsBlob();
        return file_attachment;
    }

    @AuraEnabled
    public static Void createQuoteLine(String parentQuoteId, String service, Decimal margin) {
        Blob file = getQuoteFiles(service, margin);
        Proto_A_Quote_Line__c newQuotedService = new Proto_A_Quote_Line__c();
        newQuotedService.Name = service;
        newQuotedService.Service_Name__c = service;
        newQuotedService.Margin__c = margin;
        newQuotedService.Proto_A_Quote__c = parentQuoteId;
        insert newQuotedService;
        // Attachment attach = new Attachment(
        //     Name = service + '.xlsx',
        //     Body = file,
        //     ContentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        //     ParentId = newQuotedService.Id
        // );
        // insert attach;
        DateTime today = System.today();
        String todayFormatted = today.format('yyyy-MM-dd');
        quoteFileAttach(newQuotedService.id, 
            service + '_' + todayFormatted + '.xlsx', 
            file);
    }

    @AuraEnabled
    public static String createNewQuote(String quoteName){
        Proto_A_Quote__c newQuote = new Proto_A_Quote__c();
        newQuote.name = quoteName;
        insert newQuote;
        return newQuote.Id;
    }
}